-- CREACION DE LAS SECUENCIAS USADAS PARA LAS TABLAS
CREATE SEQUENCE CLIENTE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE ESTADO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE PEDIDOS_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE PEDIDDO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE DETALLE_PEDIDO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE PRODUCTO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

-- CREACION DE LA TABLA CLIENTE
CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER DEFAULT CLIENTE_SEQ.NEXTVAL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    TELEFONO NUMBER(10,0) NOT NULL,
    DIRECCION VARCHAR2(100),
    CONSTRAINT TELEFONO_UNIQUE UNIQUE(TELEFONO),
    CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL),
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)

);

-- CREACION DE LA TABLA PRODUCTOS
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER DEFAULT PRODUCTO_SEQ.NEXTVAL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(300) NOT NULL,
    PRECIO DECIMAL (10, 2) NOT NULL,
    STOCK NUMBER NOT NULL,
    CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

-- CREACION DE LA TABLA ESTADO
CREATE TABLE ESTADO (ID_ESTADO NUMBER DEFAULT ESTADO_SEQ.NEXTVAL, 
                     ESTADO VARCHAR2(50) NOT NULL,
                     CONSTRAINT ESTADO_PK PRIMARY KEY (ID_ESTADO)
);

-- CREACION DE LA TABLA PEDIDOS
CREATE TABLE PEDIDOS(ID_PEDIDO NUMBER DEFAULT PEDIDDO_SEQ.NEXTVAL, ID_CLIENTE NUMBER NOT NULL,
TOTAL NUMBER(10,2), FECHA_CREACION DATE, ESTADO VARCHAR2(50), CONSTRAINT PEDIDOS_PK PRIMARY KEY (ID_PEDIDO)
);

-- CREACION DE LA TABLA PEDIDO_PRODUCTO
CREATE TABLE PEDIDO_PRODUCTO (ID_PEDIDO NUMBER NOT NULL, ID_PRODUCTO NUMBER NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL, DESCRIPCION  VARCHAR2(100) NOT NULL, PRECIO NUMBER(10, 2), CANTIDAD NUMBER,
CONSTRAINT PEDIDO_PRODUCTO_FK FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);


-- REGISTROS PARA TABLA ESTADOS
INSERT INTO ESTADO(estado) VALUES('Pendiente');  
INSERT INTO ESTADO(estado) VALUES('Enviado');  
INSERT INTO ESTADO(estado) VALUES('Entregado');  
INSERT INTO ESTADO(estado) VALUES('Cancelado');
