CREATE SEQUENCE PRODUCTO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER DEFAULT PRODUCTO_SEQ.NEXTVAL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(300) NOT NULL,
    PRECIO DECIMAL (10, 2) NOT NULL,
    STOCK NUMBER NOT NULL,
    CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);
